version: "3.9"
services:
    trainsim-payment-service:
        image: maven:3.8.1-openjdk-11
        command: mvn exec:java -pl trainsim-payment-service
        working_dir: /source
        volumes:
            - .:/source
            - .m2:/root/.m2
        ports:
            - 8003:80
        environment:
            MAVEN_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1044